import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import Astro from "../components/Astro";
import Bella from "../components/Bella";
import Code from "../components/Code";
import Hero from "../components/Hero";
import Hover from "../components/Hover";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>GSAP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer>
        <Hero />
        <h1>test</h1>
      </HomeContainer>
    </>
  );
};

export default Home;

const HomeContainer = styled.div`
  background-color: var(--bgc);
  display: grid;
  place-items: center;
`;
